# Generated by Django 5.2.8 on 2025-11-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='proyectos/', verbose_name='Imagen')),
                ('link_repo', models.URLField(blank=True, null=True, verbose_name='Enlace GitHub')),
                ('link_demo', models.URLField(blank=True, null=True, verbose_name='Enlace Demo/Web')),
                ('tecnologias', models.CharField(max_length=200, verbose_name='Tecnologías (separadas por coma)')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-created'],
            },
        ),
    ]
