# Generated by Django 5.2.8 on 2025-11-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título Principal')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='carousel/', verbose_name='Imagen de Fondo')),
                ('button_text', models.CharField(default='Ver más', max_length=50, verbose_name='Texto del Botón')),
                ('button_link', models.CharField(default='#proyectos', max_length=200, verbose_name='Enlace (ej: #contacto)')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Slide del Carrusel',
                'verbose_name_plural': 'Slides del Carrusel',
                'ordering': ['order'],
            },
        ),
    ]
