# Generated by Django 5.2.8 on 2025-11-25 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_carouselitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre Habilidad')),
                ('icon', models.CharField(blank=True, max_length=10, verbose_name='Icono/Emoji')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['created'],
            },
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='button_link',
            field=models.CharField(default='#proyectos', max_length=200, verbose_name='Enlace'),
        ),
    ]
