# Generated by Django 5.2.8 on 2025-11-25 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_skill_alter_carouselitem_button_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='icon',
        ),
    ]
