# Generated by Django 5.2.8 on 2025-11-25 14:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_mensaje'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['-fecha_desarrollo'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_desarrollo',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Realización'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida'),
        ),
    ]
