# Generated by Django 5.2.8 on 2025-11-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_proyecto_options_proyecto_fecha_desarrollo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre interno (ej: CV Python)')),
                ('codigo_acceso', models.CharField(max_length=7, unique=True, verbose_name='Clave de Seguridad')),
                ('archivo', models.FileField(upload_to='cvs/', verbose_name='Archivo PDF')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Curriculum Protegido',
                'verbose_name_plural': 'Curriculums Protegidos',
            },
        ),
    ]
