# Generated by Django 5.2.8 on 2025-11-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_curriculum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título Principal (ej: Hola, soy Karla)')),
                ('subtitulo', models.CharField(max_length=150, verbose_name='Subtítulo (ej: Desarrolladora Web Full Stack)')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfil/', verbose_name='Foto de Perfil/Tecnológica')),
                ('bio_parrafo1', models.TextField(verbose_name='Párrafo 1 (Mi Enfoque)')),
                ('bio_parrafo2', models.TextField(blank=True, null=True, verbose_name='Párrafo 2 (Experiencia)')),
                ('bio_parrafo3', models.TextField(blank=True, null=True, verbose_name='Párrafo 3 (Compromiso)')),
            ],
            options={
                'verbose_name': 'Perfil Personal',
                'verbose_name_plural': 'Perfil Personal (¡Solo 1!)',
            },
        ),
    ]
