# Generated by Django 5.2.8 on 2025-11-26 19:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre de Tecnología')),
            ],
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil Personal', 'verbose_name_plural': 'Perfil Personal'},
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='subtitulo',
            field=models.CharField(max_length=150, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título Principal'),
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='tecnologias',
        ),
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Certificación')),
                ('institucion', models.CharField(max_length=100, verbose_name='Institución')),
                ('fecha_obtencion', models.DateField(default=django.utils.timezone.now)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='book.perfil', verbose_name='Perfil Asociado')),
            ],
            options={
                'verbose_name': 'Certificación Destacada',
                'verbose_name_plural': 'Certificaciones',
            },
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título del Cargo')),
                ('empresa', models.CharField(max_length=100, verbose_name='Empresa')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='book.perfil', verbose_name='Perfil asociado')),
            ],
            options={
                'verbose_name': 'Experiencia Laboral',
                'verbose_name_plural': 'Experiencia Laboral',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tecnologias',
            field=models.ManyToManyField(to='book.tecnologia', verbose_name='Tecnologías usadas'),
        ),
    ]
