# Generated by Django 5.2.8 on 2025-11-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_tecnologia_alter_perfil_options_alter_perfil_foto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificacion',
            name='perfil',
        ),
        migrations.DeleteModel(
            name='Tecnologia',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='tecnologias',
            field=models.ManyToManyField(blank=True, related_name='proyectos', to='book.skill', verbose_name='Tecnologías usadas'),
        ),
        migrations.DeleteModel(
            name='Certificacion',
        ),
    ]
